name: monorepo_example_bug
repository: https://github.com/invertase/melos

packages:
  - packages/*
  - packages/*/example

command:
  bootstrap:
    environment:
      sdk: ">=3.2.0 <4.0.0"
      flutter: ">=3.19.0"

scripts:
